title: Rahul Raj
description: Digital Reflection of Me
url: "https://rahulrajpandey.github.io"
baseurl: "" 
theme: null
default_og_image: "/assets/images/og_default.png"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-optional-front-matter
  - jekyll-include-cache


jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'

collections:
  projects:
    output: true
    permalink: /projects/:path/

permalink: /blog/:title/

exclude: [vendor, node_modules]
