title: Rahul Raj
description: Digital Reflection of Me
url: "https://rahulrajpandey.github.io"
baseurl: "" 
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-optional-front-matter
  - jekyll-include-cache


jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'